version: "2"
services:
  web:
    image: web
    build:
      context: ../../../..
      dockerfile: ./scripts/deploy/dev/web/Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
        - SERVICE=web
    ports:
      - "8080:8080"